## LAST_FM

In [3]:
import spotipy
from spotipy.oauth2 import SpotifyClientCredentials
import pandas as pd
import time
import requests, time, re, html
from io import BytesIO
from dotenv import load_dotenv
import os

In [ ]:
load_dotenv()
my_API_KEY = os.getenv("LASTFM_API_KEY")
SHARED_SECRET = os.getenv("LASTFM_SHARED_SECRET")

In [4]:
def get_artist_info(artist_name): # Generamos una función para obtener de la API la información de los artistas seleccionados en la extracción de la API de Spotipy
    API_KEY = my_API_KEY 
    BASE_URL = "https://ws.audioscrobbler.com/2.0/" # Conexión a la API de LastFM

    params = {
        "method": "artist.getinfo",
        "artist": artist_name,
        "api_key": API_KEY,
        "format": "json",
        "autocorrect": 1,
        "lang": "en"
    }                                               # Parametros dados a la API para la extración en el endpoint "artist.getinfo"

    response = requests.get(BASE_URL, params=params)
    data = response.json() 

    # Validar si hay error
    if "error" in data:
        print(f"❌ Error: {data['message']}")
        return None

    artist = data["artist"]
    listeners = artist["stats"]["listeners"]
    playcount = artist["stats"]["playcount"]
    similar_artists = [a["name"] for a in artist["similar"]["artist"]]
    similar_artist = similar_artists[0] if similar_artists else None
     # Información de cada canción según los parametros explicitos

    bio = data.get("artist", {}).get("bio", {})
    summary = bio.get("summary",{})

    return {
        "artist_name": artist["name"],
        "biography": summary,
        "listeners": listeners,
        "playcount": playcount,
        "similar_artist": similar_artist
    } # Formato para mostrar la información

In [44]:
# Incluir aquí el CSV de los datos de Spotify

In [5]:
df_spotify = pd.read_csv("Canciones_Spotify.csv")  # Transformación en DataFrame
df_spotify.head()

,id,track_name,artist_name,year,genre,album_type,release_date,popularity
0,1WHNqqRWhJVZIdCScFKtl5,Washington on Your Side,Leslie Odom Jr.,2015,soundtrack,album,2015-09-25,66
1,1DLfR4MOfLYbV6v3xrmWa8,We Know,Lin-Manuel Miranda,2015,soundtrack,album,2015-09-25,66
2,2AtC6i0b8TjpjhWBZYLprX,Bonetrousle,Toby Fox,2015,soundtrack,album,2015-09-15,58
3,6oF8ueLn5hIl4PRp17sxW6,That Would Be Enough,Phillipa Soo,2015,soundtrack,album,2015-09-25,67
4,46YSff2Rq1ZtN1YVk5cwbZ,Brave Shine,Aimer,2015,soundtrack,album,2015-07-29,61

In [6]:
df_spotify['artist_name'].tolist() # Creación de lista de artistas para ejecutar en archivo "artistas_LastFM.ipynb"

['Leslie Odom Jr.',
 'Lin-Manuel Miranda',
 'Toby Fox',
 'Phillipa Soo',
 'Aimer',
 'Original Broadway Cast of Hamilton',
 'Bear McCreary',
 'Fear, and Loathing in Las Vegas',
 'Okieriete Onaodowan',
 'Toby Fox',
 'Lin-Manuel Miranda',
 'Daveed Diggs',
 'Original Broadway Cast of Hamilton',
 'Leslie Odom Jr.',
 'Daveed Diggs',
 'Christopher Jackson',
 'Original Broadway Cast of Hamilton',
 'Toby Fox',
 'Lin-Manuel Miranda',
 'Jonathan Groff',
 'Leslie Odom Jr.',
 'Toby Fox',
 'Toby Fox',
 'Leslie Odom Jr.',
 'Toby Fox',
 'Lin-Manuel Miranda',
 'Phillipa Soo',
 'Toby Fox',
 'Jasmine Cephas-Jones',
 'Original Broadway Cast of Hamilton',
 'Toby Fox',
 'Leslie Odom Jr.',
 'Leslie Odom Jr.',
 'Thayne Jasperson',
 'Leslie Odom Jr.',
 'KANA-BOON',
 'Michael Giacchino',
 'Leslie Odom Jr.',
 'Jonathan Groff',
 'Lin-Manuel Miranda',
 'Goose house',
 'Renée Elise Goldsberry',
 'John Williams',
 'Toby Fox',
 'Toby Fox',
 'Lin-Manuel Miranda',
 'Phillipa Soo',
 'Bear McCreary',
 'Toby Fox',
 'Leslie Odom Jr.',
 'Toby Fox',
 'Toby Fox',
 'Ariana DeBose',
 'Toby Fox',
 'Toby Fox',
 'Toby Fox',
 'Toby Fox',
 'Toby Fox',
 'Michael Giacchino',
 'Phillipa Soo',
 'Eir Aoi',
 'Lin-Manuel Miranda',
 'Kazuya Yoshii',
 'Renée Elise Goldsberry',
 'Christopher Jackson',
 'Leslie Odom Jr.',
 'Toby Fox',
 'The Barden Bellas',
 'Toby Fox',
 'Ramin Djawadi',
 'Christopher Jackson',
 'Agrupacion Musical Nuestro Padre Jesús Despojado de Jaen',
 'Marcin Przybyłowicz',
 'Christopher Jackson',
 'Marcin Przybyłowicz',
 'John Williams',
 'Toby Fox',
 'Trevor Morris',
 'Dario Marianelli',
 'Toby Fox',
 'Bear McCreary',
 'Ryuichi Sakamoto',
 'Lin-Manuel Miranda',
 'Toby Fox',
 'Roque Baños',
 'Toby Fox',
 'Basil Poledouris',
 'Original Broadway Cast of Hamilton',
 'Phillipa Soo',
 'Toby Fox',
 'Toby Fox',
 'Toby Fox',
 'Toby Fox',
 'Craig Armstrong',
 'Jonathan Groff',
 'Marcin Przybyłowicz',
 'Toby Fox',
 'Mikolai Stroinski',
 'BRADIO',
 'Lin-Manuel Miranda',
 'Donna Burke',
 'SIE Sound Team',
 'CHiCO with HoneyWorks',
 'Percival Schuttenbach',
 'Ólafur Arnalds',
 'Sho Oosawa',
 'Toby Fox',
 'Patrick Doyle',
 'Toby Fox',
 'Bear McCreary',
 'Peter Gregson',
 'Super DJ Yuuki',
 'Yutaka Yamada',
 'John Williams',
 'Toby Fox',
 'Harry Gregson-Williams',
 'Roque Baños',
 'Toby Fox',
 'Patrick Doyle',
 'James Newton Howard',
 'Aqua Timez',
 'SIE Sound Team',
 'Toby Fox',
 'Toby Fox',
 'GENERATIONS from EXILE TRIBE',
 'Patrick Doyle',
 'Mikolai Stroinski',
 'Toby Fox',
 'The Barden Bellas',
 'Das Sound Machine',
 'Toby Fox',
 'Dario Marianelli',
 'Virgen de los Reyes',
 'Bear McCreary',
 'Mikolai Stroinski',
 'Craig Armstrong',
 'Bear McCreary',
 'Toby Fox',
 'Toby Fox',
 'Marcin Przybyłowicz',
 'Mikolai Stroinski',
 'Toby Fox',
 'Virgen de los Reyes',
 'Toby Fox',
 'LiSA',
 'Toby Fox',
 'Konomi Suzuki',
 'Gareth Coker',
 'Bear McCreary',
 'Toby Fox',
 'Ramin Djawadi',
 'Yugo Kanno',
 'Geek Music',
 'Christopher Fitzgerald',
 'DEAN FUJIOKA',
 '3年E組うた担(渚&茅野&業&磯貝&前原)',
 'Yuki Hayashi',
 'RADWIMPS',
 'Ramin Djawadi',
 'Ramin Djawadi',
 'Crush',
 'James Newton Howard',
 'Piotr Musiał',
 'Kyle Dixon & Michael Stein',
 'Hans Zimmer',
 'THE ORAL CIGARETTES',
 'BURNOUT SYNDROMES',
 'Ryan Gosling',
 'Max Richter',
 'Fernando Velázquez',
 'RADWIMPS',
 'Hans Zimmer',
 'Ramin Djawadi',
 'Emma Stone',
 'Fernando Velázquez',
 'Max Richter',
 'MAN WITH A MISSION',
 'Ben Platt',
 'SID',
 'RADWIMPS',
 'MOB CHOIR',
 'Fernando Velázquez',
 'Emma Stone',
 'JAM Project',
 'John Legend',
 'Rupert Gregson-Williams',
 'Ryan Gosling',
 'Ryan Gosling',
 'Justin Hurwitz',
 'Kyle Dixon & Michael Stein',
 'La La Land Cast',
 'Ramin Djawadi',
 'Yuki Hayashi',
 'Fernando Velázquez',
 'Fernando Velázquez',
 'BURNOUT SYNDROMES',
 'Ramin Djawadi',
 'RADWIMPS',
 'Justin Hurwitz',
 'Ryan Gosling',
 'Ramin Djawadi',
 'Yugo Kanno',
 'CHEN',
 'Adrian Barba',
 'DAVICHI',
 'Hans Zimmer',
 'BUMP OF CHICKEN',
 '7!!',
 'Christopher Tin',
 'Kimiko Glenn',
 'YOON MIRAE',
 'Aests',
 'Adrian Barba',
 'GUMMY',
 'Ramin Djawadi',
 'Michael Giacchino',
 'エミリア(CV:高橋李依)',
 'Fernando Velázquez',
 'Yuki Hayashi',
 'Elmer Bernstein',
 'Ramin Djawadi',
 'RADWIMPS',
 'Hans Zimmer',
 'RADWIMPS',
 'Marcin Przybyłowicz',
 'Ramin Djawadi',
 'kensuke ushio',
 'Mikolai Stroinski',
 'Ramin Djawadi',
 '梶浦 由記',
 'amazarashi',
 'Rupert Gregson-Williams',
 'Nicholas Britell',
 'Haruka Tomatsu',
 'Yoko Shimomura',
 'Yoko Shimomura',
 'Piotr Musiał',
 'Henry Jackman',
 'Yuki Hayashi',
 'Ramin Djawadi',
 'Justin Hurwitz',
 '3年E組うた担(渚&茅野&業&磯貝&前原)',
 'Rupert Gregson-Williams',
 'Tina Guo',
 'Rupert Gregson-Williams',
 'James Newton Howard',
 'Yuki Hayashi',
 'Fernando Velázquez',
 'Rupert Gregson-Williams',
 'James Newton Howard',
 'Ramin Djawadi',
 'YOON MIRAE',
 'Jessie Mueller',
 'Ramin Djawadi',
 'Epik High',
 'Johan Söderqvist',
 'Cynthia Erivo',
 'Jessie Mueller',
 'Shiro SAGISU',
 'DAVICHI',
 'SOYOU',
 'Kyle Dixon & Michael Stein',
 'Thomas Newman',
 'Dessa',
 'Rupert Gregson-Williams',
 'Theodore Shapiro',
 'Ramin Djawadi',
 'Kyle Dixon & Michael Stein',
 'Chris Remo',
 'Sam Kim',
 'WEAVER',
 'Agrupación Musical Jesús Cautivo de Estepona',
 'Rupert Gregson-Williams',
 'Marcin Przybyłowicz',
 'Percival Schuttenbach',
 'Kyle Dixon & Michael Stein',
 'Tsuko G.',
 'Hans Zimmer',
 'Piotr Musiał',
 'Hans Zimmer',
 'Justin Hurwitz',
 'Henry Jackman',
 'Hans Zimmer',
 'SPYAIR',
 'Michael Giacchino',
 'RADWIMPS',
 'Amamiya Sora',
 'Sayuri',
 'Mick Gordon',
 'Max Richter',
 'LeeHi',
 'Chris Remo',
 'Henry Jackman',
 'Piotr Musiał',
 'RADWIMPS',
 'Craig Armstrong',
 'Max Richter',
 'Paolo Buonvino',
 'Johan Söderqvist',
 'The Meridian Studio Ensemble',
 'MYTH & ROID',
 'Mike Faist',
 'Lyn',
 'Lyn',
 'Sawano Hiroyuki',
 'Lyn',
 'Sawano Hiroyuki',
 'Christopher Larkin',
 'Bear McCreary',
 'Christy Altomare',
 'Christopher Larkin',
 'Christopher Larkin',
 'Hans Zimmer',
 'Animelmack',
 'amazarashi',
 'Charlie Clouser',
 'The Bellas',
 'Lyn',
 'Michelle Williams',
 'Linked Horizon',
 'Lyn',
 'Hugh Jackman',
 'Linked Horizon',
 'Ólafur Arnalds',
 'Christopher Larkin',
 'PornoGraffitti',
 'Linked Horizon',
 'Kenshi Yonezu',
 'Ben Platt',
 'Hugh Jackman',
 'Christopher Larkin',
 'Sawano Hiroyuki',
 'Ziv Zaifman',
 'Ramin Djawadi',
 'Hugh Jackman',
 'D-51',
 'Hans Zimmer',
 'Linked Horizon',
 'Christopher Larkin',
 'Loren Allred',
 'Zac Efron',
 'Christopher Larkin',
 'Keala Settle',
 'Christopher Larkin',
 'Hugh Jackman',
 'Loren Allred',
 'Keala Settle',
 'Austyn Johnson',
 'Zac Efron',
 'Hugh Jackman',
 'Ben Platt',
 'The Bellas',
 'Hans Zimmer',
 'AILEE',
 'The New Barden Bellas',
 'Tia',
 'Ben Platt',
 'The Bellas',
 'Yasuharu Takanashi',
 'Heize',
 'Ben Platt',
 'Kyle Dixon & Michael Stein',
 'Miura Jam',
 'deadman 死人',
 'MIYAVI',
 'Lyn',
 'Sawano Hiroyuki',
 'Christopher Larkin',
 'MYTH & ROID',
 'Sawano Hiroyuki',
 'Kiyoshi Hikawa',
 'The Bellas',
 'Sawano Hiroyuki',
 'Christopher Larkin',
 'MYTH & ROID',
 'Benjamin Wallfisch',
 'Yuki Hayashi',
 'Christopher Larkin',
 'Steve Jablonsky',
 'Christopher Larkin',
 'Christopher Larkin',
 'Ramin Djawadi',
 'Christopher Larkin',
 'Rupert Gregson-Williams',
 'Ramin Djawadi',
 'Christopher Larkin',
 'Christopher Larkin',
 'Daniel Pemberton',
 'Christopher Larkin',
 'Hans Zimmer',
 'Lyn',
 'Steve Jablonsky',
 'Christopher Larkin',
 'Christopher Larkin',
 'Christopher Larkin',
 'Hans Zimmer',
 'Steve Jablonsky',
 'Christopher Larkin',
 'Christopher Larkin',
 'Ramin Djawadi',
 'アトラスサウンドチーム',
 'Laura Dreyfuss',
 'Chitose Morinaga',
 'Nostalghia',
 'GUMI',
 'Rachel Bay Jones',
 'Daniel Pemberton',
 'Anly',
 'Christy Altomare',
 'Angelo Badalamenti',
 'Sam Lee',
 'Kevin Penkin',
 'JUNNA',
 'Lyn',
 'NateWantsToBattle',
 'Lyn',
 'Rachel Bay Jones',
 'LiSA',
 'Ramin Djawadi',
 'Machico',
 'HENRY',
 'Machico',
 'Ryan Gosling',
 'cinema staff',
 'The Bellas',
 'アトラスサウンドチーム',
 'アトラスサウンドチーム',
 '岡部啓一',
 'Michael Giacchino',
 'Kristofer Maddigan',
 'Christopher Larkin',
 'Sawano Hiroyuki',
 'Hans Zimmer',
 'Angelo Badalamenti',
 'Yuki Hayashi',
 'Hans Zimmer',
 'Joris de Man',
 'La Sentencia',
 'Konomi Suzuki',
 'Hans Zimmer',
 'Konomi Suzuki',
 'Thomas Newman',
 'LiSA',
 'Sarah Schachner',
 'Christopher Larkin',
 'X-Ray Dog',
 'Brian the Sun',
 'Christopher Larkin',
 'The Bellas',
 'Christopher Larkin',
 'Aaron Montalvo',
 'Christopher Larkin',
 'UVERworld',
 '遠野高志',
 'Cher',
 'Hugh Skinner',
 'YOSHIKI',
 'SIX',
 'TK from Ling tosite sigure',
 'Toby Fox',
 'Toby Fox',
 'SIX',
 'Lily James',
 'Jeremy Irvine',
 'Toby Fox',
 'Linked Horizon',
 'Christopher Larkin',
 'Yugo Kanno',
 'Yugo Kanno',
 'Amanda Seyfried',
 'Toby Fox',
 'Amanda Seyfried',
 '物語シリーズ',
 'Justin Hurwitz',
 'Brian Tyler',
 'Lily James',
 'KANKAKU PIERO',
 'ムービー・サウンズ・アンリミテッド',
 'Lenny code fiction',
 '桜島麻衣(CV:瀬戸麻沙美)',
 'Cher',
 'MYTH & ROID',
 'Colin Firth',
 'VK Blanka',
 'Hugh Skinner',
 'ASIAN KUNG-FU GENERATION',
 'Lily James',
 'Christine Baranski',
 'Coda',
 'Amanda Seyfried',
 'Lily James',
 'James Newton Howard',
 'VK Blanka',
 'YOSHIKI',
 'Josh Dylan',
 'LiSA',
 'Manu Guix',
 'Manu Guix',
 'Creepy Nuts',
 'Trevor Jones',
 'Ben Platt',
 'Varian',
 'Kelly Clarkson',
 'SIX',
 'Ari Afsar',
 'Taylor Louderman',
 'Daichi Miura',
 'BiSH',
 'Kelly Clarkson',
 'SIX',
 'Geek Music',
 'Daniel Pemberton',
 'Toby Fox',
 'SIX',
 'Yoko Takahashi',
 'Lily James',
 'Berlinist',
 'Lily James',
 'Survive Said The Prophet',
 'Manu Guix',
 'Justin Hurwitz',
 'Toby Fox',
 'Christopher Larkin',
 'OxT',
 'Toby Fox',
 'Bradley Cooper',
 'Geoff Zanelli',
 'Manu Guix',
 'Bradley Cooper',
 'Ramin Djawadi',
 'Manu Guix',
 'いとうかなこ',
 'SID',
 'MAX',
 'Manu Guix',
 'Toby Fox',
 'Christopher Larkin',
 'Toby Fox',
 'Manu Guix',
 'Cher',
 'Lily James',
 'Manu Guix',
 'Bear McCreary',
 'Kumi Koda',
 'Justin Hurwitz',
 'Manu Guix',
 'SIX',
 'Toby Fox',
 'みゆな',
 'Manu Guix',
 'Dan Romer',
 'Friedrich Habetler',
 'Geek Music',
 'JEONG SEWOON',
 'Shonan No Kaze',
 'SIX',
 'SIX',
 'Berioska',
 'Kate Rockwell',
 'Grey Henson',
 'Friedrich Habetler',
 'ZAQ',
 'Hans Zimmer',
 'Toby Fox',
 'Manu Guix',
 'SIX',
 'Christopher Larkin',
 'Christopher Larkin',
 'Lena Raine',
 'Macarena García',
 'FLOW',
 'Evan Call',
 'Meryl Streep',
 'Linked Horizon',
 'Craig David',
 'FLOW',
 '桜島麻衣(CV:瀬戸麻沙美)',
 'Panos Mouzourakis',
 'The Flight',
 'Hans Zimmer',
 'Manu Guix',
 'vegeta',
 'Mili',
 'Toby Fox',
 'Bear McCreary',
 'Manu Guix',
 'Manu Guix',
 'Toby Fox',
 'Evan Call',
 'Manu Guix',
 'Friedrich Habetler',
 'Willow Sage Hart',
 'Akano',
 'The Rising Storm',
 '藤田真由美',
 'Toby Fox',
 'Olly Alexander (Years & Years)',
 'Manu Guix',
 'John Paesano',
 'Brian Tyler',
 'Alex Brightman',
 'Hildur Guðnadóttir',
 'Mika Nakashima',
 'MOB CHOIR',
 'André De Shields',
 'Hans Zimmer',
 'sumika',
 'Kyle Dixon & Michael Stein',
 '高橋\u3000洋子',
 'QUEEN BEE',
 'Ludwig Göransson',
 'coldrain',
 'Ramin Djawadi',
 'Cö shu Nie',
 'ALI',
 'Ramin Djawadi',
 'Casey Edwards',
 'ALI',
 'Alan Silvestri',
 '中野家の五つ子',
 'Mrs. GREEN APPLE',
 'UVERworld',
 'James Newton Howard',
 'Taron Egerton',
 'Hans Zimmer',
 'Thomas Newman',
 'Yugo Kanno',
 'UVERworld',
 'Ramin Djawadi',
 'Ramin Djawadi',
 'MAN WITH A MISSION',
 'Trevor Morris',
 'Seiko Oomori',
 'Thomas Newman',
 'Survive Said The Prophet',
 'Andrew Prahlow',
 '美波',
 'Agrupación Musical Nuestro Padre Jesús de la Redención de Sevilla',
 'Andrew Prahlow',
 'Andrew Prahlow',
 'Akano',
 'Ramin Djawadi',
 'Max Richter',
 'Linked Horizon',
 'Ramin Djawadi',
 'Linked Horizon',
 'Agrupación Musical Nuestro Padre Jesús de la Redención de Sevilla',
 'Andrew Prahlow',
 'Mrs. GREEN APPLE',
 'LiSA',
 'Carrie Hope Fletcher',
 'André De Shields',
 'Tricker',
 'Alex Brightman',
 'RoomTone',
 'Jamie Muscato',
 'Steven Universe',
 'FictionJunction',
 'Masayuki Suzuki',
 'DAVICHI',
 'YOON MIRAE',
 'Sophia Anne Caruso',
 'Vishal-Shekhar',
 'Trevor Morris',
 'Alan Silvestri',
 'Hans Zimmer',
 'Ramin Djawadi',
 '須田景凪',
 "T'Shan Williams",
 'John Powell',
 'Ludvig Forssell',
 'cinema staff',
 'Hans Zimmer',
 'Alan Silvestri',
 'Eva Noblezada',
 'Trevor Morris',
 'Ramin Djawadi',
 'Alex Brightman',
 'Steven Price',
 'Hiroshi Kitadani',
 'KANKAKU PIERO',
 'Andrew Prahlow',
 'Miyu Tomita',
 'Agrupacion Musical Nuestro Padre Jesús Despojado de Jaen',
 'André De Shields',
 'Andrew Prahlow',
 'ASCA',
 'Max Richter',
 'Sawano Hiroyuki',
 'the peggies',
 'Hans Zimmer',
 'Hans Zimmer',
 'Hans Zimmer',
 'Akano',
 'Yugo Kanno',
 'Sawano Hiroyuki',
 'Hans Zimmer',
 'Andrew Prahlow',
 'MADKID',
 'LiSA',
 'King Gnu',
 'Hadestown Original Broadway Company',
 'Pawel Blaszczak',
 'Hadestown Original Broadway Company',
 'Hans Zimmer',
 'André De Shields',
 'UVERworld',
 'Taron Egerton',
 'Ricky Rojas',
 'Eva Noblezada',
 'RADWIMPS',
 'Hans Zimmer',
 'Hildur Guðnadóttir',
 'Sawano Hiroyuki',
 'Aaron Tveit',
 'Casey Edwards',
 'Hans Zimmer',
 'Alexandre Desplat',
 'Ramin Djawadi',
 'UVERworld',
 'Hans Zimmer',
 'Nicholas Britell',
 'ALI',
 'Hans Zimmer',
 'Kyle Dixon & Michael Stein',
 'Heize',
 'Thomas Newman',
 'Agrupación Musical Nuestro Padre Jesús de la Redención de Sevilla',
 'Andrew Prahlow',
 'Ramin Djawadi',
 'Danny Burstein',
 'Creepy Nuts',
 'Hans Zimmer',
 'MADKID',
 'Nicholas Britell',
 'Arijit Singh',
 'Andrew Prahlow',
 '10CM',
 'Reeve Carney',
 'Andrew Prahlow',
 'Andrew Prahlow',
 'Reeve Carney',
 'Agrupacion Musical Nuestro Padre Jesús Despojado de Jaen',
 'EMPiRE',
 'Sawano Hiroyuki',
 'Marc Streitenfeld',
 'Clinton Shorter',
 'Hans Zimmer',
 'Akano',
 'Sawano Hiroyuki',
 'Collo',
 'Jay A',
 'Krunoslav Kićo Slabinac',
 'Ivo Pattiera',
 'Tereza Kesovija',
 'Группа 101',
 'Urbanus',
 'Đani Maršan',
 "Prajoth D'sa",
 'Krunoslav Kićo Slabinac',
 'Stan Van Samang',
 'Hari Rončević',
 'Datuk Ahmad Jais',
 'Badal Paul',
 'Группа 101',
 'Stan Van Samang',
 'Klapa Maslina',
 'Ivo Pattiera',
 'Lalitya Munshaw',
 'Группа 101',
 'Tereza Kesovija',
 'Sarah Ndagire',
 'Jay Jay',
 'Sarah Ndagire',
 'Krunoslav Kićo Slabinac',
 'Айкын',
 'Hari Rončević',
 'Tereza Kesovija',
 'Badal Paul',
 'Stimela',
 'Valeriya',
 'Badal Paul',
 'Krunoslav Kićo Slabinac',
 'Ivo Pattiera',
 'Krunoslav Kićo Slabinac',
 'Lalitya Munshaw',
 'Krunoslav Kićo Slabinac',
 'Krunoslav Kićo Slabinac',
 'Ivo Pattiera',
 'Klapa Puntamika',
 'Azad Amedê',
 'Cho Yong Pil',
 'Krunoslav-Kićo Slabinac',
 'Aidar BMM',
 'Jabu Khanyile',
 'Sarah Ndagire',
 'Tereza Kesovija',
 'Đani Maršan',
 'Айкын',
 'Park Mi Kyung',
 'Meri Cetinic',
 'Edita Sopjani',
 'Joo Yein',
 'Kwaya Ya Uinjilisti Ya Vijana Arusha Mjini',
 'Krunoslav Kićo Slabinac',
 'Krunoslav-Kićo Slabinac',
 'Lalitya Munshaw',
 'Lalitya Munshaw',
 'Đani Maršan',
 'Tamer Günaydın',
 'Aidar BMM',
 'Đani Maršan',
 'Dalmatino',
 'Lalitya Munshaw',
 'Meri Cetinic',
 'Cho Yong Pil',
 'Ivo Pattiera',
 'Klapa Puntamika',
 'Aidar BMM',
 'As One',
 'Hızır Acil',
 'Badal Paul',
 'Айкын',
 'Jabu Khanyile',
 'Đani Maršan',
 'Айкын',
 'Judith Sephuma',
 'Группа 101',
 'Dilnaz Akhmadiyeva',
 'Арай',
 'Hızır Acil',
 'Tomislav Ivčić',
 'Tural Everest',
 'Đani Maršan',
 'Afrigo Band',
 'Klapa Cambi',
 'Klapa Sufit',
 'Đani Maršan',
 'Meri Cetinic',
 'Tereza Kesovija',
 'Krunoslav Kićo Slabinac',
 'Tomislav Ivčić',
 'Tereza Kesovija',
 'Raj Negi',
 'Natali',
 'As One',
 'Stan Van Samang',
 'Арай',
 'Badal Paul',
 'Sarah Ndagire',
 'Raj Negi',
 'Badal Paul',
 'As One',
 'Sunny Hill',
 'Tereza Kesovija',
 'Stella Mengele',
 'Stan Van Samang',
 'Meri Cetinic',
 'Badal Paul',
 'Lissa Lewis',
 'Krunoslav Kićo Slabinac',
 'Sarah Ndagire',
 'Jay Jay',
 'Drain',
 'Valeriya',
 'Sarah Ndagire',
 'Jasna Zlokic',
 'Sarah Ndagire',
 'Aidar BMM',
 'Айкын',
 'Ivo Pattiera',
 'Herman Basudde',
 'Ivo Pattiera',
 'FauloCity',
 'Tomislav Bralic',
 'Krunoslav Kićo Slabinac',
 'Арай',
 'Jungyup',
 'Sarah Ndagire',
 'Meri Cetinic',
 'Afrigo Band',
 'Tedi Spalato',
 'Stan Van Samang',
 'Группа 101',
 'Vinko Coce',
 'Dinara Sultan',
 'Judith Sephuma',
 "Prajoth D'sa",
 'Jasna Zlokic',
 'Группа 101',
 'Krunoslav Kićo Slabinac',
 'Tereza Kesovija',
 'Krunoslav Kićo Slabinac',
 'Klapa Puntamika',
 'Tereza Kesovija',
 'Đani Maršan',
 'Lee Seung Chul',
 'Đani Maršan',
 'Suzy',
 'Арай',
 'Iwan Esseboom',
 'Amani',
 'Amani',
 'Flaka Krelani',
 'Lalitya Munshaw',
 'Klapa Cambi',
 'Tereza Kesovija',
 'Han All',
 'Meri Cetinic',
 'Tereza Kesovija',
 'Klapa Cambi',
 'Flaka Krelani',
 'Da Gudda Jazz',
 'Tomislav Ivčić',
 'Meri Cetinic',
 'Veli Sahiti',
 'Kim Young-Im',
 'Stan Van Samang',
 'Ruken',
 'Lee Mi Ja',
 'MAKTUB',
 '2LSON',
 'Remzie Osmani',
 'Jagmohan Digari',
 'Kim Young-Im',
 'Jasna Zlokic',
 'Naveen Pathak',
 'Lawrence P Dsouza',
 'Veli Sahiti',
 'OKDAL',
 'Naveen Pathak',
 'Naveen Pathak',
 'Stan Van Samang',
 'Tereza Kesovija',
 'Iwan Esseboom',
 'Tereza Kesovija',
 'Nam Jin',
 'Naveen Pathak',
 'Kim Young-Im',
 'Jay Jay',
 'Meri Cetinic',
 'Kim Young-Im',
 'Tereza Kesovija',
 'Meri Cetinic',
 'Koen Crucke',
 'Ivo Pattiera',
 'Gold Ag',
 'Stan Van Samang',
 'Amani',
 'Da Gudda Jazz',
 'Tereza Kesovija',
 'Meri Cetinic',
 'Ivo Pattiera',
 'Tereza Kesovija',
 'Tereza Kesovija',
 'Flaka Krelani',
 'Lissa Lewis',
 'Veli Sahiti',
 'Iwan Esseboom',
 'Klapa Sveti Juraj HRM',
 'Tereza Kesovija',
 'Bae Ho',
 'Nikolay Baskov',
 'Tereza Kesovija',
 'Stan Van Samang',
 'Meri Cetinic',
 'Kim Young-Im',
 'Sunny Hill',
 'Iwan Esseboom',
 'Jagmohan Digari',
 'Nikolay Baskov',
 'Lalitya Munshaw',
 'Kim Young-Im',
 'Lalitya Munshaw',
 'Patti Kim',
 'Lalitya Munshaw',
 'Kim Young-Im',
 'Koen Crucke',
 'Lee Mi Ja',
 'Klapa Iskon',
 'Tereza Kesovija',
 'Idiot Glee',
 'Natali',
 'Iwan Esseboom',
 'Lee Mi Ja',
 'Kim Young-Im',
 'Koen Crucke',
 'Tereza Kesovija',
 'Klapa Sufit',
 'Jeon Sang Keun',
 'Ronny Mosuse',
 'Vinko Coce',
 'Lawrence P Dsouza',
 'Veli Sahiti',
 'Flaka Krelani',
 'Klapa Sveti Juraj HRM',
 'Kim Young-Im',
 'Johan Kim',
 'Prelude',
 'Stan Van Samang',
 ...]

In [7]:
len(df_spotify['artist_name'].tolist()) # Número de registros de la extración de datos de la API Spotipy

3000

In [8]:
unique_artists_spotify = df_spotify['artist_name'].unique().tolist() # Generar valores únicos de artistas de la extración de datos de la API Spotipy

In [9]:
len(unique_artists_spotify) # Número de registros unicos de artistas de la extración de datos de la API Spotipy

1201

In [50]:
lista_artist_lastfm_NN = [] # Variable para almacenar toda la información de todos los artistas que no sean nulos.

for X in unique_artists_spotify:
    info = get_artist_info(X)
    if info is not None:  # solo agrega si tiene datos
        lista_artist_lastfm_NN.append(info)
    time.sleep(0.5)

❌ Error: The artist you supplied could not be found
❌ Error: The artist you supplied could not be found
❌ Error: The artist you supplied could not be found

In [1]:
len(lista_artist_lastfm_NN) # Número de registros unicos de artistas de la extración de datos de la API LastFM

NameError: name 'lista_artist_lastfm_NN' is not defined

In [54]:
df_lastfm = pd.DataFrame(lista_artist_lastfm_NN) # Transformación en DataFrame

In [55]:
df_lastfm

,artist_name,biography,listeners,playcount,similar_artist
0,Leslie Odom Jr.,"Leslie Odom, Jr (born August 6, 1981) is an Am...",783654,33526440,Christopher Jackson
1,Lin-Manuel Miranda,"Lin-Manuel Miranda (born January 16, 1980 in N...",690836,24963003,Leslie Odom Jr.
2,Toby Fox,Toby Fox is an American developer and composer...,1110128,134239421,Lena Raine
3,Phillipa Soo,"Phillipa Soo (born May 31, 1990) is an America...",547924,14230247,Christopher Jackson
4,Aimer,There are at least 4 artists who go by Aimer:\...,446718,23143896,ReoNa
...,...,...,...,...,...
1193,Amaarae,"Ama Serwah Genfi (born July 4, 1994), known pr...",935034,30374468,Rochelle Jordan
1194,Chris Brown,"Christopher Maurice Brown (born May 5, 1989) i...",4598461,146850181,Chris Brown & Tyga
1195,Lola Jane,"<a href=""https://www.last.fm/music/Lola+Jane""...",5731,50670,Archie & Sizzle
1196,Duda,There are two groups using the name Duda one f...,6635,69758,Peled
1197,Simone Vitullo,Simone Vitullo DJ and house music producer for...,21699,101880,Chambord

In [56]:
df_lastfm.to_csv("Artistas_LastFM.csv", index=False) #Extraccion LastFM to CSV

In [11]:
df_artists_lastfm = pd.read_csv("Artistas_LastFM.csv") # Lectura de CSV
df_artists_lastfm

,artist_name,biography,listeners,playcount,similar_artist
0,Leslie Odom Jr.,"Leslie Odom, Jr (born August 6, 1981) is an Am...",783654,33526440,Christopher Jackson
1,Lin-Manuel Miranda,"Lin-Manuel Miranda (born January 16, 1980 in N...",690836,24963003,Leslie Odom Jr.
2,Toby Fox,Toby Fox is an American developer and composer...,1110128,134239421,Lena Raine
3,Phillipa Soo,"Phillipa Soo (born May 31, 1990) is an America...",547924,14230247,Christopher Jackson
4,Aimer,There are at least 4 artists who go by Aimer:\...,446718,23143896,ReoNa
...,...,...,...,...,...
1193,Amaarae,"Ama Serwah Genfi (born July 4, 1994), known pr...",935034,30374468,Rochelle Jordan
1194,Chris Brown,"Christopher Maurice Brown (born May 5, 1989) i...",4598461,146850181,Chris Brown & Tyga
1195,Lola Jane,"<a href=""https://www.last.fm/music/Lola+Jane""...",5731,50670,Archie & Sizzle
1196,Duda,There are two groups using the name Duda one f...,6635,69758,Peled
1197,Simone Vitullo,Simone Vitullo DJ and house music producer for...,21699,101880,Chambord

In [13]:
def clean_html_links(text):
    if not isinstance(text, str):
        return text
    
    # Reemplaza <a href="URL">texto</a> → URL
    text = re.sub(r'<a href="(https?://[^"]+)".*?>.*?</a>', r'\1', text)

    # Quita cualquier otra etiqueta HTML que quede
    text = re.sub(r'<.*?>', '', text)

    return text.strip()


df_artists_lastfm = pd.read_csv("Artistas_LastFM.csv")

for i, artist in enumerate(df_artists_lastfm["artist_name"], start=1):
    biography_text = df_artists_lastfm.loc[i-1, "biography"]     
    cleaned_text = clean_html_links(biography_text)    #aquí limpiamos el codigo HTML
    df_artists_lastfm.loc[i-1, "biography"] = cleaned_text  #guardamos el texto limpio en la misma celda
    print(f"{i}. ✅ {artist}")
    time.sleep(0.25)

1. ✅ Leslie Odom Jr.
2. ✅ Lin-Manuel Miranda
3. ✅ Toby Fox
4. ✅ Phillipa Soo
5. ✅ Aimer
6. ✅ Original Broadway Cast of Hamilton
7. ✅ Bear McCreary
8. ✅ Fear, and Loathing in Las Vegas
9. ✅ Okieriete Onaodowan
10. ✅ Daveed Diggs
11. ✅ Christopher Jackson
12. ✅ Jonathan Groff
13. ✅ Jasmine Cephas-Jones
14. ✅ Thayne Jasperson
15. ✅ KANA-BOON
16. ✅ Michael Giacchino
17. ✅ Goose house
18. ✅ Renée Elise Goldsberry
19. ✅ John Williams
20. ✅ Ariana DeBose
21. ✅ Eir Aoi
22. ✅ Kazuya Yoshii
23. ✅ The Barden Bellas
24. ✅ Ramin Djawadi
25. ✅ Agrupacion Musical Nuestro Padre Jesús Despojado de Jaen
26. ✅ Marcin Przybyłowicz
27. ✅ Trevor Morris
28. ✅ Dario Marianelli
29. ✅ 坂本龍一
30. ✅ Roque Baños
31. ✅ Basil Poledouris
32. ✅ Craig Armstrong
33. ✅ Mikolai Stroinski
34. ✅ BRADIO
35. ✅ Donna Burke
36. ✅ SIE Sound Team
37. ✅ CHiCO with HoneyWorks
38. ✅ Percival Schuttenbach
39. ✅ Ólafur Arnalds
40. ✅ Sho Oosawa
41. ✅ Patrick Doyle
42. ✅ Peter Gregson
43. ✅ Super DJ Yuuki
44. ✅ Yutaka Yamada
45. ✅ Harry Gregson-Williams
46. ✅ James Newton Howard
47. ✅ Aqua Timez
48. ✅ GENERATIONS from EXILE TRIBE
49. ✅ Das Sound Machine
50. ✅ Virgen de los Reyes
51. ✅ Lisa
52. ✅ 鈴木このみ
53. ✅ Gareth Coker
54. ✅ 菅野祐悟
55. ✅ Geek Music
56. ✅ Christopher Fitzgerald
57. ✅ Dean Fujioka
58. ✅ 3年E組うた担(渚&茅野&業&磯貝&前原)
59. ✅ 林ゆうき
60. ✅ RADWIMPS
61. ✅ Crush
62. ✅ Piotr Musiał
63. ✅ Kyle Dixon & Michael Stein
64. ✅ Hans Zimmer
65. ✅ THE ORAL CIGARETTES
66. ✅ BURNOUT SYNDROMES
67. ✅ Ryan Gosling
68. ✅ Max Richter
69. ✅ Fernando Velázquez
70. ✅ Emma Stone
71. ✅ MAN WITH A MISSION
72. ✅ Ben Platt
73. ✅ Sid
74. ✅ MOB CHOIR
75. ✅ JAM Project
76. ✅ John Legend
77. ✅ Rupert Gregson-Williams
78. ✅ Justin Hurwitz
79. ✅ La La Land Cast
80. ✅ Chen
81. ✅ Adrian Barba
82. ✅ DAVICHI
83. ✅ BUMP OF CHICKEN
84. ✅ 7!!
85. ✅ Christopher Tin
86. ✅ Kimiko Glenn
87. ✅ Yoon Mirae
88. ✅ aests
89. ✅ Gummy
90. ✅ エミリア(CV:高橋李依)
91. ✅ Elmer Bernstein
92. ✅ Kensuke Ushio
93. ✅ 梶浦由記
94. ✅ amazarashi
95. ✅ Nicholas Britell
96. ✅ 戸松遥
97. ✅ 下村陽子
98. ✅ Henry Jackman
99. ✅ Tina Guo
100. ✅ Jessie Mueller
101. ✅ Epik High
102. ✅ Johan Söderqvist
103. ✅ Cynthia Erivo
104. ✅ 鷺巣詩郎
105. ✅ SOYOU
106. ✅ Thomas Newman
107. ✅ Dessa
108. ✅ Theodore Shapiro
109. ✅ Chris Remo
110. ✅ Sam Kim
111. ✅ Weaver
112. ✅ Agrupación Musical Jesús Cautivo de Estepona
113. ✅ Tsuko G.
114. ✅ SPYAIR
115. ✅ Amamiya Sora
116. ✅ Sayuri
117. ✅ Mick Gordon
118. ✅ LEE HI
119. ✅ Paolo Buonvino
120. ✅ The Meridian Studio Ensemble
121. ✅ MYTH & ROID
122. ✅ Mike Faist
123. ✅ Lyn
124. ✅ 澤野弘之
125. ✅ Christopher Larkin
126. ✅ Christy Altomare
127. ✅ Animelmack
128. ✅ Charlie Clouser
129. ✅ The Bellas
130. ✅ Michelle Williams
131. ✅ Linked Horizon
132. ✅ Hugh Jackman
133. ✅ ポルノグラフィティ
134. ✅ 米津玄師
135. ✅ Ziv Zaifman
136. ✅ D-51
137. ✅ Loren Allred
138. ✅ Zac Efron
139. ✅ Keala Settle
140. ✅ Austyn Johnson
141. ✅ 에일리
142. ✅ The New Barden Bellas
143. ✅ Tia
144. ✅ Yasuharu Takanashi
145. ✅ Heize
146. ✅ Miura Jam
147. ✅ deadman 死人
148. ✅ 雅-MIYAVI-
149. ✅ 氷川きよし
150. ✅ Benjamin Wallfisch
151. ✅ Steve Jablonsky
152. ✅ Daniel Pemberton
153. ✅ アトラスサウンドチーム
154. ✅ Laura Dreyfuss
155. ✅ Chitose Morinaga
156. ✅ Nostalghia
157. ✅ Gumi
158. ✅ Rachel Bay Jones
159. ✅ Anly
160. ✅ Angelo Badalamenti
161. ✅ Sam Lee
162. ✅ Kevin Penkin
163. ✅ JUNNA
164. ✅ NateWantsToBattle
165. ✅ MACHICO
166. ✅ Henry
167. ✅ cinema staff
168. ✅ 岡部啓一
169. ✅ Kristofer Maddigan
170. ✅ Joris de Man
171. ✅ La Sentencia
172. ✅ Sarah Schachner
173. ✅ X-Ray Dog
174. ✅ Brian the Sun
175. ✅ Aaron Montalvo
176. ✅ UVERworld
177. ✅ 遠野高志
178. ✅ Cher
179. ✅ Hugh Skinner
180. ✅ YOSHIKI
181. ✅ SIX
182. ✅ TK from 凛として時雨
183. ✅ Lily James
184. ✅ Jeremy Irvine
185. ✅ Amanda Seyfried
186. ✅ 物語シリーズ
187. ✅ Brian Tyler
188. ✅ Kankaku Piero
189. ✅ ムービー・サウンズ・アンリミテッド
190. ✅ Lenny code fiction
191. ✅ 桜島麻衣(CV:瀬戸麻沙美)
192. ✅ Colin Firth
193. ✅ VK Blanka
194. ✅ ASIAN KUNG-FU GENERATION
195. ✅ Christine Baranski
196. ✅ Coda
197. ✅ Josh Dylan
198. ✅ Manu Guix
199. ✅ Creepy Nuts
200. ✅ Trevor Jones
201. ✅ Varian
202. ✅ Kelly Clarkson
203. ✅ Ari Afsar
204. ✅ Taylor Louderman
205. ✅ 三浦大知
206. ✅ Bish
207. ✅ Yoko Takahashi
208. ✅ Berlinist
209. ✅ Survive Said The Prophet
210. ✅ OxT
211. ✅ Bradley Cooper
212. ✅ Geoff Zanelli
213. ✅ いとうかなこ
214. ✅ MAX
215. ✅ 倖田來未
216. ✅ みゆな
217. ✅ Dan Romer
218. ✅ Friedrich Habetler
219. ✅ JEONG SEWOON
220. ✅ Shonan no kaze
221. ✅ Berioska
222. ✅ Kate Rockwell
223. ✅ Grey Henson
224. ✅ ZAQ
225. ✅ Lena Raine
226. ✅ Macarena García
227. ✅ Flow
228. ✅ Evan Call
229. ✅ Meryl Streep
230. ✅ Craig David
231. ✅ Panos Mouzourakis
232. ✅ The Flight
233. ✅ Vegeta
234. ✅ Mili
235. ✅ Willow Sage Hart
236. ✅ AKano
237. ✅ The Rising Storm
238. ✅ 藤田真由美
239. ✅ Olly Alexander (Years & Years)
240. ✅ John Paesano
241. ✅ Alex Brightman
242. ✅ Hildur Guðnadóttir
243. ✅ 中島美嘉
244. ✅ André De Shields
245. ✅ Sumika
246. ✅ 高橋洋子
247. ✅ Queen Bee
248. ✅ Ludwig Göransson
249. ✅ coldrain
250. ✅ Cö shu Nie
251. ✅ Ali
252. ✅ Casey Edwards
253. ✅ Alan Silvestri
254. ✅ 中野家の五つ子
255. ✅ Mrs. GREEN APPLE
256. ✅ Taron Egerton
257. ✅ 大森靖子
258. ✅ Andrew Prahlow
259. ✅ 美波
260. ✅ Agrupación Musical Nuestro Padre Jesús de la Redención de Sevilla
261. ✅ Carrie Hope Fletcher
262. ✅ Tricker
263. ✅ Roomtone
264. ✅ Jamie Muscato
265. ✅ Steven Universe
266. ✅ FictionJunction
267. ✅ Masayuki Suzuki
268. ✅ Sophia Anne Caruso
269. ✅ Vishal-Shekhar
270. ✅ 須田景凪
271. ✅ T'Shan Williams
272. ✅ John Powell
273. ✅ Ludvig Forssell
274. ✅ Eva Noblezada
275. ✅ Steven Price
276. ✅ Hiroshi Kitadani
277. ✅ Miyu Tomita
278. ✅ ASCA
279. ✅ the peggies
280. ✅ Madkid
281. ✅ King Gnu
282. ✅ Hadestown Original Broadway Company
283. ✅ Paweł Błaszczak
284. ✅ Ricky Rojas
285. ✅ Aaron Tveit
286. ✅ Alexandre Desplat
287. ✅ Danny Burstein
288. ✅ Arijit Singh
289. ✅ 10cm
290. ✅ Reeve Carney
291. ✅ Empire
292. ✅ Marc Streitenfeld
293. ✅ Clinton Shorter
294. ✅ Collo
295. ✅ Jay A
296. ✅ krunoslav kićo slabinac
297. ✅ Ivo Pattiera
298. ✅ Tereza Kesovija
299. ✅ Группа 101
300. ✅ Urbanus
301. ✅ Đani Maršan
302. ✅ Prajoth D'sa
303. ✅ Stan Van Samang
304. ✅ HARI RONČEVIĆ
305. ✅ Datuk Ahmad Jais
306. ✅ Badal Paul
307. ✅ Klapa Maslina
308. ✅ Lalitya Munshaw
309. ✅ Sarah Ndagire
310. ✅ Jay Jay
311. ✅ Айкын
312. ✅ Stimela
313. ✅ Валерия
314. ✅ KLAPA PUNTAMIKA
315. ✅ Azad Amedê
316. ✅ Cho Yong Pil
317. ✅ Krunoslav-Kićo Slabinac
318. ✅ Aidar BMM
319. ✅ Jabu Khanyile
320. ✅ Park Mi Kyung
321. ✅ Meri Cetinic
322. ✅ Edita Sopjani
323. ✅ Joo Yein
324. ✅ Kwaya Ya Uinjilisti Ya Vijana Arusha Mjini
325. ✅ Tamer Günaydın
326. ✅ Dalmatino
327. ✅ As One
328. ✅ Hızır Acil
329. ✅ Judith Sephuma
330. ✅ Dilnaz Akhmadiyeva
331. ✅ Арай
332. ✅ Tomislav Ivčić
333. ✅ Tural Everest
334. ✅ Afrigo Band
335. ✅ Klapa Cambi
336. ✅ klapa Šufit
337. ✅ Raj Negi
338. ✅ Natali
339. ✅ Sunny Hill
340. ✅ Stella Mengele
341. ✅ Lissa Lewis
342. ✅ Drain
343. ✅ Jasna Zlokic
344. ✅ Herman basudde
345. ✅ FauloCity
346. ✅ Tomislav Bralić
347. ✅ Jungyup
348. ✅ Tedi Spalato
349. ✅ Vinko Coce
350. ✅ Dinara Sultan
351. ✅ 이승철
352. ✅ Suzy
353. ✅ Iwan Esseboom
354. ✅ Amani
355. ✅ Flaka Krelani
356. ✅ Han All
357. ✅ Da Gudda Jazz
358. ✅ Veli Sahiti
359. ✅ Kim Young-Im
360. ✅ RUKEN
361. ✅ Lee Mi Ja
362. ✅ MakTub
363. ✅ 2lson
364. ✅ Remzie Osmani
365. ✅ Jagmohan Digari
366. ✅ Naveen Pathak
367. ✅ Lawrence P Dsouza
368. ✅ Okdal
369. ✅ Nam Jin
370. ✅ Koen Crucke
371. ✅ Gold Ag
372. ✅ Klapa Sveti Juraj HRM
373. ✅ Bae Ho
374. ✅ Nikolay Baskov
375. ✅ Patti Kim
376. ✅ Klapa Iskon
377. ✅ Idiot Glee
378. ✅ Jeon Sang Keun
379. ✅ Ronny Mosuse
380. ✅ johan kim
381. ✅ Prelude
382. ✅ Jaison Sequeira
383. ✅ YOONWON
384. ✅ Dayangku Intan
385. ✅ Avril
386. ✅ Choi Jinhee
387. ✅ Vicmass Luodollar
388. ✅ Ajay Warriar
389. ✅ M. Nasir
390. ✅ Әбдіжаппар Әлқожа
391. ✅ Иса Алимуса
392. ✅ Tim Sameke
393. ✅ Secret Asian Men
394. ✅ Jelle Cleymans
395. ✅ Sabri Fejzullahu
396. ✅ Mans
397. ✅ Suraj Sahu
398. ✅ Fanta Damba
399. ✅ Ильяз Андаш
400. ✅ Nameless
401. ✅ Say Sue Me
402. ✅ Homeboy
403. ✅ Kizzy
404. ✅ Kim Wan-sun
405. ✅ Kent Valley
406. ✅ KLAPA CAMBI (KAŠTEL KAMBELOVAC)
407. ✅ Əбдіжаппар Əлқожа
408. ✅ Ulf Peder Olrog
409. ✅ J
410. ✅ The Barberettes
411. ✅ Leonora Jakupi
412. ✅ Iowa
413. ✅ Ali Okapov
414. ✅ Chris Perry
415. ✅ Руслан Абылов
416. ✅ Jo Dong Jin
417. ✅ Emon
418. ✅ Roumadyval
419. ✅ Havin
420. ✅ 12mé
421. ✅ Lee Moon Sae
422. ✅ DD Smash
423. ✅ Beşir Kaya
424. ✅ Blinky Bill
425. ✅ Hozan Canê
426. ✅ Satish
427. ✅ NO_ON
428. ✅ Hozan Şervan
429. ✅ King Kaka
430. ✅ Koma Dilan
431. ✅ Bily Acoustie
432. ✅ Jaguar
433. ✅ Satish Sawariya Yadav
434. ✅ 김범룡
435. ✅ juho
436. ✅ HHP
437. ✅ Cemre Kamacıoğlu
438. ✅ Sherif Omeri
439. ✅ Fedyz
440. ✅ Meena Rana
441. ✅ LEES2UN
442. ✅ Song Hee-ran
443. ✅ Taner Eyüpoğlu
444. ✅ Deniz Deman
445. ✅ kumar pritam
446. ✅ 鄧麗君
447. ✅ Yeong Rok Jeon
448. ✅ MAP6
449. ✅ Bart Peeters
450. ✅ IMFACT
451. ✅ Mr Seed
452. ✅ Ermal Fejzullahu
453. ✅ Space Cowboy
454. ✅ Kairat Nurtas
455. ✅ Asheem Mangoli
456. ✅ Dinçer
457. ✅ Halo
458. ✅ BAND JA NAIMON! MAXX NAKAYOSHI
459. ✅ Hozan Serwan
460. ✅ Milan Das
461. ✅ Guru negi
462. ✅ Alba
463. ✅ Norwegian Wood
464. ✅ Женя Ангел
465. ✅ WABLE
466. ✅ Burhan Toprak
467. ✅ DASHXX
468. ✅ Lee Minhyuk
469. ✅ Bismilli Çeto
470. ✅ Lee Heemoon
471. ✅ quttay
472. ✅ Hozan Reşo
473. ✅ De Mens
474. ✅ Abyken
475. ✅ Mina Rana
476. ✅ NST & The Soul Sauce
477. ✅ HOZAN MUZAFFER
478. ✅ Rabbit
479. ✅ Hozan Aytaç
480. ✅ Hella Chluy
481. ✅ Jang Pill Soon
482. ✅ Poligraf Sharikoff
483. ✅ Mihalis Violaris
484. ✅ Wi Il Cheong
485. ✅ Madeleine
486. ✅ DPNS
487. ✅ Saro Vardanyan
488. ✅ LEEWOO
489. ✅ Blerta Kosova
490. ✅ Adult Child
491. ✅ Aka
492. ✅ Klapa Kampanel
493. ✅ Inder Arya
494. ✅ 이현
495. ✅ Lee Eun Mi
496. ✅ The Night Of Seokyo
497. ✅ Şevval Sam
498. ✅ Owais Bhatt
499. ✅ 윤종신
500. ✅ Dr Malinga
501. ✅ Martin Garrix
502. ✅ Dimitri Vegas & Like Mike
503. ✅ Avicii
504. ✅ Gregory Porter
505. ✅ Paul Kalkbrenner
506. ✅ Alesso
507. ✅ Yves Larock
508. ✅ The Chemical Brothers
509. ✅ Janji
510. ✅ Caravan Palace
511. ✅ Tiësto
512. ✅ Hardwell
513. ✅ Cascada
514. ✅ Cartoon
515. ✅ Marilyn Manson
516. ✅ Crazy P
517. ✅ Kygo
518. ✅ Robin Schulz
519. ✅ Mr. Probz
520. ✅ Major Lazer
521. ✅ Claptone
522. ✅ PASTEL GHOST
523. ✅ Otto Knows
524. ✅ Michael Calfan
525. ✅ Zedd
526. ✅ Calvin Harris
527. ✅ Eric Prydz
528. ✅ Joris Voorn
529. ✅ DJ Pantelis
530. ✅ Jack Ü
531. ✅ Deorro
532. ✅ David Guetta
533. ✅ Parov Stelar
534. ✅ Sidewalks and Skeletons
535. ✅ Armin van Buuren
536. ✅ Ian van Dahl
537. ✅ Galantis
538. ✅ Vicetone
539. ✅ Carpenter Brut
540. ✅ Vigiland
541. ✅ Tujamo
542. ✅ Deaf Kev
543. ✅ Tungevaag
544. ✅ Il Est Vilaine
545. ✅ Italobrothers
546. ✅ Dom Dolla
547. ✅ Jetta
548. ✅ Lorn
549. ✅ Fantasy Project
550. ✅ Rival Consoles
551. ✅ Widinson
552. ✅ NTO
553. ✅ Jess Glynne
554. ✅ Saison
555. ✅ St. Germain
556. ✅ R3hab
557. ✅ Sander van Doorn
558. ✅ Felix Jaehn
559. ✅ New Limit
560. ✅ Tim Deluxe
561. ✅ Chancha Via Circuito
562. ✅ Marbert Rocel
563. ✅ Good Times Ahead
564. ✅ Dimitri Vangelis & Wyman
565. ✅ Flo Rida
566. ✅ The Weeknd
567. ✅ Feint
568. ✅ Faithless
569. ✅ Nicola Cruz
570. ✅ Moderator
571. ✅ Jean Michel Jarre
572. ✅ NERVO
573. ✅ Panda Eyes
574. ✅ Purple Disco Machine
575. ✅ She Past Away
576. ✅ Marlena Shaw
577. ✅ Lost Frequencies
578. ✅ Joachim Pastor
579. ✅ Bosq
580. ✅ Molly Nilsson
581. ✅ Patty Ray
582. ✅ Jim Yosef
583. ✅ Degiheugi
584. ✅ Ltj Xperience
585. ✅ Dillon Francis
586. ✅ Moguai
587. ✅ League of Legends
588. ✅ ZHU
589. ✅ Makj
590. ✅ Elektronomia
591. ✅ Dave
592. ✅ The Irrepressibles
593. ✅ Alaia & Gallo
594. ✅ Unknown Brain
595. ✅ Fedde Le Grand
596. ✅ Massive Attack
597. ✅ Warriyo
598. ✅ Marshmello
599. ✅ Cristoph
600. ✅ Sia
601. ✅ Alan Walker
602. ✅ RÜFÜS DU SOL
603. ✅ DJ Snake
604. ✅ Burak Yeter
605. ✅ Kungs
606. ✅ Club Des Belugas
607. ✅ Quantic
608. ✅ Ofenbach
609. ✅ Jan Blomqvist
610. ✅ Alok
611. ✅ Sash!
612. ✅ Mike Posner
613. ✅ W&W
614. ✅ Cash Cash
615. ✅ Kollektiv Turmstrasse
616. ✅ Orange Sector
617. ✅ Porter Robinson
618. ✅ Dan Zamani
619. ✅ The Chainsmokers
620. ✅ FM-84
621. ✅ Skepta
622. ✅ Syn Cole
623. ✅ AronChupa
624. ✅ The Midnight
625. ✅ FÄIS
626. ✅ FrankJavCee
627. ✅ Tremenda Jauría
628. ✅ Boogie Belgique
629. ✅ The Bahama Soul Club
630. ✅ Starparty
631. ✅ Kamaliza
632. ✅ Crystal Castles
633. ✅ Axwell
634. ✅ Madness Gangsters
635. ✅ Cuartero
636. ✅ Imagination
637. ✅ Las Bistecs
638. ✅ Moderat
639. ✅ Sak Noel
640. ✅ Waldeck
641. ✅ Stereoclip
642. ✅ Kinobe
643. ✅ STEVE MONITE
644. ✅ Redfoo
645. ✅ DJ Gollum
646. ✅ Lane 8
647. ✅ OMFG
648. ✅ Jo Cohen
649. ✅ Jl & Afterman
650. ✅ Fun Factory
651. ✅ Mike Perry
652. ✅ Calyx & TeeBee
653. ✅ James
654. ✅ MATTN
655. ✅ Melody Gardot
656. ✅ KSHMR
657. ✅ Stavroz
658. ✅ Mop Mop
659. ✅ Zouzoulectric
660. ✅ TheFatRat
661. ✅ Whilk & Misky
662. ✅ Tritonal
663. ✅ La Yegros
664. ✅ Soulwax
665. ✅ Christian Löffler
666. ✅ Romare
667. ✅ Cappella
668. ✅ Charli xcx
669. ✅ GFOTY
670. ✅ Oxia
671. ✅ The xx
672. ✅ Lost Sky
673. ✅ Gianluca Vacchi
674. ✅ Dj Dasten
675. ✅ Tom Tyger
676. ✅ Bruno Martini
677. ✅ Suga7
678. ✅ Jamiroquai
679. ✅ Fisher
680. ✅ Vitalic
681. ✅ Skrillex
682. ✅ Eskorzo
683. ✅ Bicep
684. ✅ Shouse
685. ✅ Emrod
686. ✅ Pascal Letoublon
687. ✅ Bob Sinclar
688. ✅ Jude & Frank
689. ✅ David Tort
690. ✅ DJ Miko
691. ✅ Machine Girl
692. ✅ Gorillaz
693. ✅ Mandragora
694. ✅ Don Diablo
695. ✅ ESPRIT 空想
696. ✅ Nightcore
697. ✅ J Hus
698. ✅ Ahrix
699. ✅ Future
700. ✅ Bonobo
701. ✅ Royal Gigolos
702. ✅ Thievery Corporation
703. ✅ Jesse Rose
704. ✅ Drunkenmunky
705. ✅ Shade K
706. ✅ SKAN
707. ✅ Shapeshifters
708. ✅ Jkriv
709. ✅ The Cancel
710. ✅ Ministry Of Funk
711. ✅ L. Doblado
712. ✅ Xinobi
713. ✅ Mister Gym
714. ✅ Parra for Cuva
715. ✅ COEO
716. ✅ BeatGhosts
717. ✅ Nuages
718. ✅ Macky Gee
719. ✅ Chase & Status
720. ✅ Tchami
721. ✅ Chemical Surf
722. ✅ Vestron Vulture
723. ✅ Dirty Palm
724. ✅ Eelke Kleijn
725. ✅ Stormzy
726. ✅ Kraftwerk
727. ✅ Populous
728. ✅ Drake
729. ✅ Terrence Parker
730. ✅ Gryffin
731. ✅ Four Tet
732. ✅ J Balvin
733. ✅ Jaja
734. ✅ Chromatics
735. ✅ Anja Schneider
736. ✅ Third Party
737. ✅ Jeb Loy Nichols
738. ✅ Timmy Trumpet
739. ✅ Patrice Rushen
740. ✅ danicpeepner
741. ✅ DJ Wady
742. ✅ Tom Novy
743. ✅ Guy Gerber
744. ✅ Getter Jaani
745. ✅ Zeus X Crona
746. ✅ Rolando
747. ✅ Dennis Cruz
748. ✅ Bellaire
749. ✅ Fatboy Slim
750. ✅ Robin Hustin
751. ✅ CHVRCHES
752. ✅ Ran-D
753. ✅ Peggy Gou
754. ✅ Dannc Steelee
755. ✅ Mathias D.
756. ✅ NOTD
757. ✅ Ben Böhmer
758. ✅ Møme
759. ✅ Calum Scott
760. ✅ Vintage Culture
761. ✅ Weiß
762. ✅ El Búho
763. ✅ Dynoro
764. ✅ David Whistle
765. ✅ baiuca
766. ✅ Cult Member
767. ✅ Aidan Swank
768. ✅ Morgan Page
769. ✅ Lebanon Hanover
770. ✅ Sophie
771. ✅ IC3PEAK
772. ✅ Fake Blood
773. ✅ Steve Aoki
774. ✅ The Prince Karma
775. ✅ Sigala
776. ✅ Nightcore Reality
777. ✅ Gaullin
778. ✅ Apashe
779. ✅ Gabry Ponte
780. ✅ Bronski Beat
781. ✅ Chris Lake
782. ✅ Sub Focus
783. ✅ La Fine Equipe
784. ✅ ATFC
785. ✅ Different Heaven
786. ✅ Traf
787. ✅ benny blanco
788. ✅ Bragolin
789. ✅ Sofi Tukker
790. ✅ Kaz James
791. ✅ Rough Traders
792. ✅ Monolink
793. ✅ Raymix
794. ✅ Drop Department
795. ✅ deadmau5
796. ✅ Babalos
797. ✅ Avoure
798. ✅ Twin Tribes
799. ✅ Traitrs
800. ✅ Calvo
801. ✅ Ours Samplus
802. ✅ Sandro Silva
803. ✅ PABLO BENDR
804. ✅ Maurice West
805. ✅ SNBRN
806. ✅ YTBS Nightcore
807. ✅ Kid Simius
808. ✅ Gramophiles
809. ✅ Mike Williams
810. ✅ Jody Wisternoff
811. ✅ Novalima
812. ✅ Moca
813. ✅ Nightmares on Wax
814. ✅ Oliver Heldens
815. ✅ Reyko
816. ✅ Henrique Camacho
817. ✅ Avalon
818. ✅ Sam Feldt
819. ✅ Ilkay Sencan
820. ✅ Rnbstylerz
821. ✅ LUM!X
822. ✅ ARTBAT
823. ✅ Riton
824. ✅ Felsenstein
825. ✅ Lucky Luke
826. ✅ K-391
827. ✅ Boris Brejcha
828. ✅ SAINt JHN
829. ✅ Meduza
830. ✅ Colectivo Panamera
831. ✅ Nico Morano
832. ✅ Kush Kush
833. ✅ Alex Rasov
834. ✅ Stromae
835. ✅ Jax Jones
836. ✅ Arlon Vibes
837. ✅ Regard
838. ✅ Yeah Yeah Yeahs
839. ✅ Dayvi
840. ✅ Las Eras
841. ✅ Marie Davidson
842. ✅ KOMPROMAT
843. ✅ AJ Tracey
844. ✅ Sound of Legend
845. ✅ Duke Dumont
846. ✅ French 79
847. ✅ Afro House Dj
848. ✅ Sean Finn
849. ✅ Ed Sheeran
850. ✅ Wiley
851. ✅ Younotus
852. ✅ Manco the Sound
853. ✅ Mazdem
854. ✅ Qodës
855. ✅ Kaaze
856. ✅ Mathame
857. ✅ Chico Rose
858. ✅ Jay-Jay Johanson
859. ✅ The Parcels
860. ✅ Hector Couto
861. ✅ Cero39
862. ✅ Michael Kiwanuka
863. ✅ Catching Flies
864. ✅ Halogen
865. ✅ dubdogz
866. ✅ Dimrain47
867. ✅ Shaed
868. ✅ Rooftime
869. ✅ Dj Esli
870. ✅ YoSoyMatt
871. ✅ Monsieur Periné
872. ✅ Jack Back
873. ✅ Tinlicker
874. ✅ Lilly Wood & The Prick
875. ✅ Young T & Bugsey
876. ✅ Jex
877. ✅ LondonGround
878. ✅ Babert
879. ✅ Carl Cox
880. ✅ Keanu Silva
881. ✅ Yeah But No
882. ✅ Bru-C
883. ✅ Rampa
884. ✅ Zero 7
885. ✅ Jeirex
886. ✅ Mabel
887. ✅ WINATI
888. ✅ BNJ
889. ✅ Pedro Capó
890. ✅ Ava Max
891. ✅ Mitú
892. ✅ Yves V
893. ✅ Estelle
894. ✅ Wizkid
895. ✅ Davido
896. ✅ Wande Coal
897. ✅ Djodje
898. ✅ Kizz Daniel
899. ✅ Bebi Philip
900. ✅ Master Jake
901. ✅ Iyanya
902. ✅ Ruff-N-Smooth
903. ✅ Eugy
904. ✅ Boy Teddy
905. ✅ Pérola
906. ✅ DjeuhDjoah
907. ✅ Ravidson
908. ✅ DREAM BOYZ
909. ✅ The Souljazz Orchestra
910. ✅ Sergio Cremonese
911. ✅ Timaya
912. ✅ Tekno
913. ✅ Jennifer Dias
914. ✅ Dotorado Pro
915. ✅ Marumo
916. ✅ Jay Oliver
917. ✅ Don Miguelo
918. ✅ Mykel Forever
919. ✅ Dele Sosimi
920. ✅ Bracket
921. ✅ Sarkodie
922. ✅ Jey V
923. ✅ C4 Pedro
924. ✅ Patoranking
925. ✅ Mr Eazi
926. ✅ Yuri Da cunha
927. ✅ Daddy Killa
928. ✅ Landrick
929. ✅ Tony Allen
930. ✅ Calema
931. ✅ Grupo Extra
932. ✅ Skales
933. ✅ Ebo Taylor
934. ✅ Burna Boy
935. ✅ Falz
936. ✅ Korede Bello
937. ✅ Dada KD
938. ✅ Kedjevara
939. ✅ Rim Kwaku Obeng
940. ✅ Ifá
941. ✅ Saaphy
942. ✅ Serge Beynaud
943. ✅ Daduh King
944. ✅ Leo beatz
945. ✅ Roberto
946. ✅ 2Much
947. ✅ Orezi
948. ✅ Fanga
949. ✅ Kcee
950. ✅ Pablo Fierro
951. ✅ Zona 5
952. ✅ Gino Latino DJ
953. ✅ DJ SHABSY
954. ✅ Lylah
955. ✅ GASMILLA
956. ✅ Flavour
957. ✅ DJ Ebou
958. ✅ Stonebwoy
959. ✅ Harrysong
960. ✅ DJ Jimmy Jatt
961. ✅ Sjava
962. ✅ Tiwa Savage
963. ✅ Amakye Dede
964. ✅ Nindja
965. ✅ Kofi Kinaata
966. ✅ Adro Warriors
967. ✅ Kaysha
968. ✅ Sauti Sol
969. ✅ London Afrobeat Collective
970. ✅ Pat Thomas
971. ✅ MDO (Menino de Ouro)
972. ✅ Julian Dj
973. ✅ Eugy Official
974. ✅ Christian Lyd
975. ✅ Lil Kesh
976. ✅ Nubiyan Twist
977. ✅ Tó Semedo
978. ✅ Joey B
979. ✅ B4
980. ✅ DJ Xclusive
981. ✅ Denis Graça
982. ✅ Kataleya
983. ✅ Dr. Paa Bobo
984. ✅ Kwaisey Pee
985. ✅ Ric Hassani
986. ✅ Staff Paulo
987. ✅ Maleek Berry
988. ✅ Yemi Alade
989. ✅ Anselmo Ralph
990. ✅ Yasmine
991. ✅ Tabanka Djaz
992. ✅ Dj Maphorisa
993. ✅ Nelson Freitas
994. ✅ Daddy Lumba
995. ✅ Kizomba Singers
996. ✅ Mika Mendes
997. ✅ Kwamz & Flava
998. ✅ Nu Genea
999. ✅ Vanda May
1000. ✅ Yta Jourias
1001. ✅ DJ Paparazzi
1002. ✅ J. Martins
1003. ✅ Puto Portugues
1004. ✅ P-Square
1005. ✅ Bisa Kdei
1006. ✅ Atım
1007. ✅ Ayo Jay
1008. ✅ RUNTOWN
1009. ✅ Badoxa
1010. ✅ Matias Damásio
1011. ✅ Alx Veliz
1012. ✅ Pasteur Lappe
1013. ✅ Nonso Amadi
1014. ✅ Olamide
1015. ✅ Phyno
1016. ✅ Cruel Santino
1017. ✅ DotMan
1018. ✅ Daasebre Gyamenah
1019. ✅ Ayisi
1020. ✅ Debordo Leekunfa
1021. ✅ Mix Premier
1022. ✅ Selebobo
1023. ✅ Shellsy Baronet
1024. ✅ William Onyeabor
1025. ✅ Mona Nicastro
1026. ✅ Loony Johnson
1027. ✅ Cerrone
1028. ✅ Brymo
1029. ✅ Messias Maricoa
1030. ✅ DJ Neptune
1031. ✅ Reekado Banks
1032. ✅ El Rego
1033. ✅ Dj Manuel Citro
1034. ✅ Babes Wodumo
1035. ✅ International Soleil Band
1036. ✅ Livy Ekemezie
1037. ✅ Darassa
1038. ✅ Caiiro
1039. ✅ Rayvanny
1040. ✅ Renegades Of Jazz
1041. ✅ Humblesmith
1042. ✅ Ycee
1043. ✅ Kranium
1044. ✅ melvitto
1045. ✅ Newen Afrobeat
1046. ✅ magnom
1047. ✅ Lil Saint
1048. ✅ AYLØ
1049. ✅ R2bees
1050. ✅ Sarz
1051. ✅ Payper Corleone
1052. ✅ VLAD IVAN
1053. ✅ Fuse ODG
1054. ✅ Girls of the Internet
1055. ✅ Floyd Lavine
1056. ✅ Oscar P
1057. ✅ Mauri Fly
1058. ✅ SHATTA WALE
1059. ✅ Simi
1060. ✅ Kidi
1061. ✅ King Promise
1062. ✅ Gabzy
1063. ✅ Luciana Abreu
1064. ✅ Soraia Ramos
1065. ✅ Manoo
1066. ✅ DJ Flex
1067. ✅ Juls
1068. ✅ Fally Ipupa
1069. ✅ Show Dem Camp
1070. ✅ puto x
1071. ✅ Krizbeatz
1072. ✅ Nana Fofie
1073. ✅ Ebony
1074. ✅ Gyedu-Blay Ambolley
1075. ✅ DeMajor
1076. ✅ Amadou & Mariam

In [14]:
df_artists_lastfm.tail(10)

,artist_name,biography,listeners,playcount,similar_artist
1188,Praiz,"Praise Ugbede Adejo (born 8 March 1984), bette...",19973,117871,illBliss
1189,Irina Barros,https://www.last.fm/music/Irina+Barros,4786,44513,Rui Orlando
1190,PAAX (Tulum),https://www.last.fm/music/PAAX+(Tulum),39889,272297,Antaares
1191,Matt Sawyer,https://www.last.fm/music/Matt+Sawyer,1755,4391,Stereo Kulisse
1192,Cubita,https://www.last.fm/music/Cubita,5383,50185,Nuno Ribeiro
1193,Amaarae,"Ama Serwah Genfi (born July 4, 1994), known pr...",935034,30374468,Rochelle Jordan
1194,Chris Brown,"Christopher Maurice Brown (born May 5, 1989) i...",4598461,146850181,Chris Brown & Tyga
1195,Lola Jane,https://www.last.fm/music/Lola+Jane,5731,50670,Archie & Sizzle
1196,Duda,There are two groups using the name Duda one f...,6635,69758,Peled
1197,Simone Vitullo,Simone Vitullo DJ and house music producer for...,21699,101880,Chambord

In [15]:
df_artists_lastfm.to_csv("Artistas_LastFM.csv", index=False) #Extraccion LastFM to CSV